version: '3.8'

services:
  node:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src/data/json:/usr/src/data/json
  # redis:
  #   image: redis:latest
  #   container_name: redis-server
  #   command: redis-server --save 1 60
  #   volumes:
  #     - ./redis-data:/data
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

# volumes:
#   redis-data:
#     driver: local
